"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files":
  [
    {
      "source": "src/_data/translations/en.json",
      "translation": "src/_data/translations/%two_letters_code%.json",
    },
  ]
