name: Synchronize with Crowdin

on:
  push:
    branches: [dev]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: crowdin/github-action@v2
        id: crowdin
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: chore/l10n
          create_pull_request: true
          commit_message: "chore(l10n): synchronize translations from Crowdin"
          pull_request_title: "chore(l10n): synchronize translations from Crowdin"
          pull_request_base_branch_name: "dev"
          skip_untranslated_strings: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Merge localization PR
        if: ${{ steps.crowdin.outputs.pull_request_number }}
        run: |
          gh pr merge -sd $PR
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR: ${{ steps.crowdin.outputs.pull_request_number }}
