name: Lint and test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  lint-and-test:
    uses: inclusive-design/workflows/.github/workflows/node-lint-and-test.yml@main
