name: Lint and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies, lint files and run tests
        run: |
          npm ci
          npm run lint
          npm run test
      - name: Save code coverage to artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: "coverage/clover.xml"
          retention-days: 5
  upload-coverage:
    name: Upload code coverage
    runs-on: ubuntu-latest
    needs:
      - lint-test
    steps:
      - name: Fetch code coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
