name: Publish release

on:
  push:
    branches: [dev]

jobs:
  release-please:
    uses: inclusive-design/workflows/.github/workflows/release-please.yml@main
    with:
      GHA_APP_ID: ${{ vars.GHA_APP_ID }}
    secrets:
      GHA_PRIVATE_KEY: ${{ secrets.GHA_PRIVATE_KEY }}
