name: Lint and test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  merge-release:
    timeout-minutes: 5
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    name: Merge tag

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: "main"
          development_branche: "dev"
          allow_ff: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
